packages:
  - "apps/web/*"
  - "apps/mobile"
  - "packages/*"

catalog:
  # React 19
  react: ^19.0.0
  react-dom: ^19.0.0
  
  # Build Tools
  vite: ^5.1.4
  "@vitejs/plugin-react": ^4.2.1
  
  # TypeScript
  typescript: ~5.5.4
  
  # Styling
  "@vanilla-extract/css": ^1.15.2
  "@vanilla-extract/recipes": ^0.5.7
  "@vanilla-extract/vite-plugin": ^4.0.0
  
  # State & Data Fetching
  "@tanstack/react-query": ^5.83.0
  jotai: ^2.13.0
  axios: ^1.6.8
  
  # Routing
  "react-router": ^7.7.1
  "react-router-dom": ^7.7.1
  
  # Supabase
  "@supabase/supabase-js": ^2.48.0
  
  # Build & Dev Tools
  "vite-plugin-dts": ^4.3.0
  turbo: ^2.5.4
  eslint: ^9.17.0
  "@eslint/js": ^9.17.0
  "typescript-eslint": ^8.19.1
  "eslint-plugin-react-hooks": ^5.1.0
  "eslint-plugin-react-refresh": ^0.4.16
